-- ═══════════════════════════════════════════════════════════
-- Migration v2: add tipo_equipa, subregiao, concelho to equipas
-- and seed ICNF/ANEPC 2026 data
-- Run on Railway: psql -c "\i migration_v2_equipas.sql"
-- ═══════════════════════════════════════════════════════════

ALTER TABLE equipas ADD COLUMN IF NOT EXISTS tipo_equipa TEXT;
ALTER TABLE equipas ADD COLUMN IF NOT EXISTS subregiao   TEXT;
ALTER TABLE equipas ADD COLUMN IF NOT EXISTS concelho    TEXT;

-- Seed data (skip duplicates by nome+subregiao+concelho)
INSERT INTO equipas (nome, tipo, tipo_equipa, subregiao, concelho)
VALUES
  ('SF 01-183', 'ESF', 'ESF', 'Alentejo Central', 'Estremoz'),
  ('SF 02-183', 'ESF', 'ESF', 'Alentejo Central', 'Portel'),
  ('SF 03-183', 'ESF', 'ESF', 'Alentejo Central', 'Borba'),
  ('ESF 01', 'ESF', 'ESF', 'Alentejo Central', 'Évora'),
  ('ESF 02', 'ESF', 'ESF', 'Alentejo Central', 'Évora'),
  ('ESF 03', 'ESF', 'ESF', 'Alentejo Central', 'Évora'),
  ('ESF 04', 'ESF', 'ESF', 'Alentejo Central', 'Évora'),
  ('ESF 05', 'ESF', 'ESF', 'Alentejo Central', 'Évora'),
  ('ESF 06', 'ESF', 'ESF', 'Alentejo Central', 'Évora'),
  ('ESF 07', 'ESF', 'ESF', 'Alentejo Central', 'Évora'),
  ('VN ALE05', 'ESF', 'VN', 'Alentejo Central', 'Évora'),
  ('VGFR 02 ALE', 'VT_ICNF', 'GFR', 'Alentejo Central', 'Évora'),
  ('VGFR 04 ALE', 'VT_ICNF', 'GFR', 'Alentejo Central', 'Évora'),
  ('SF 04-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Odemira'),
  ('SF 05-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Grândola'),
  ('SF 06-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Sines'),
  ('SF 07-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Sines'),
  ('SF 08-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Odemira'),
  ('SF 09-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Odemira'),
  ('SF 10-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Odemira'),
  ('ESF 06-181', 'ESF', 'ESF', 'Alentejo Litoral', 'Santiago do Cacém'),
  ('ESF 31-00', 'ESF', 'ESF', 'Alentejo Litoral', 'Santiago do Cacém'),
  ('ICNF 2001', 'ESF', 'VN', 'Alentejo Litoral', 'Odemira'),
  ('ICNF 3100', 'ESF', 'VN', 'Alentejo Litoral', 'Santiago do Cacém'),
  ('VN ALE08', 'ESF', 'VN', 'Alentejo Litoral', 'Santiago do Cacém'),
  ('VN20 03', 'ESF', 'VN', 'Alentejo Litoral', 'Odemira'),
  ('VAFR 01 ALE', 'VT_ICNF', 'GFR', 'Alentejo Litoral', 'Alcácer do Sal'),
  ('VASG 01 ALE', 'VT_ICNF', 'GFR', 'Alentejo Litoral', 'Alcácer do Sal'),
  ('VGFR 05 ALE', 'VT_ICNF', 'GFR', 'Alentejo Litoral', 'Santiago do Cacém'),
  ('CNAF 39', 'VTEC', 'CNAF', 'Alentejo Litoral', 'Alcácer do Sal'),
  ('CNAF 53', 'VTEC', 'CNAF', 'Alentejo Litoral', 'Santiago do Cacém'),
  ('CNAF 55', 'VTEC', 'CNAF', 'Alentejo Litoral', 'Santiago do Cacém'),
  ('SF 02-150', 'ESF', 'ESF', 'Algarve', 'Loulé'),
  ('SF 03-150', 'ESF', 'ESF', 'Algarve', 'Alcoutim'),
  ('SF 15-150', 'ESF', 'ESF', 'Algarve', 'Faro'),
  ('SF 04-150', 'ESF', 'ESF', 'Algarve', 'Monchique'),
  ('SF 16-150', 'ESF', 'ESF', 'Algarve', 'Faro'),
  ('SF 05-150', 'ESF', 'ESF', 'Algarve', 'Silves'),
  ('SF 07-150', 'ESF', 'ESF', 'Algarve', 'Portimão'),
  ('SF 09-150', 'ESF', 'ESF', 'Algarve', 'Vila Real de Santo António'),
  ('SF 10-150', 'ESF', 'ESF', 'Algarve', 'Lagos'),
  ('SF 11-150', 'ESF', 'ESF', 'Algarve', 'Lagos'),
  ('SF 12-150', 'ESF', 'ESF', 'Algarve', 'Monchique'),
  ('SF 13-150', 'ESF', 'ESF', 'Algarve', 'São Brás de Alportel'),
  ('SF 14-150', 'ESF', 'ESF', 'Algarve', 'Lagos'),
  ('SF 18-150', 'ESF', 'ESF', 'Algarve', 'Silves'),
  ('SF 19-150', 'ESF', 'ESF', 'Algarve', 'Loulé'),
  ('SF 20-150', 'ESF', 'ESF', 'Algarve', 'Silves'),
  ('ESF 06-150', 'ESF', 'ESF', 'Algarve', 'Aljezur'),
  ('ESF 08-150', 'ESF', 'ESF', 'Algarve', 'Tavira'),
  ('ICNF 2000', 'ESF', 'VN', 'Algarve', 'Aljezur'),
  ('ICNF 2200', 'ESF', 'VN', 'Algarve', 'Olhão'),
  ('ICNF 2201', 'ESF', 'VN', 'Algarve', 'Loulé'),
  ('ICNF 3200', 'ESF', 'VN', 'Algarve', 'Castro Marim'),
  ('ESF 15-150', 'ESF', 'ESF', 'Algarve', 'Silves'),
  ('ESF 16-150', 'ESF', 'ESF', 'Algarve', 'Silves'),
  ('ESF 17-150', 'ESF', 'ESF', 'Algarve', 'Silves'),
  ('MR 10 ICNF', 'MR', 'UNM_FSBF', 'Algarve', 'Loulé'),
  ('MR ICNF 06', 'MR', 'UNM_FSBF', 'Algarve', 'Loulé'),
  ('PM 08 ICNF', 'PM', 'UNM_FSBF', 'Algarve', 'Olhão'),
  ('PM_ICNF_09', 'VALE', 'UNM_FSBF', 'Algarve', 'Loulé'),
  ('VLCI 13 FSBF', 'VLCI', 'FSBF', 'Algarve', 'Olhão'),
  ('VLCI 22 FSBF', 'VLCI', 'FSBF', 'Algarve', 'Olhão'),
  ('VAFR 24 FSBF', 'VLCI', 'FSBF', 'Algarve', 'Loulé'),
  ('VAFR 01 ALG', 'VT_ICNF', 'GFR', 'Algarve', 'Olhão'),
  ('VAFR 02 ALG', 'VT_ICNF', 'GFR', 'Algarve', 'Olhão'),
  ('VASG01_ALG', 'VT_ICNF', 'GFR', 'Algarve', 'Olhão'),
  ('VAFR 03 ALG', 'VT_ICNF', 'GFR', 'Algarve', 'Olhão'),
  ('VASG 10 FSBF', 'VT_ICNF', 'FSBF', 'Algarve', 'Olhão'),
  ('VGFR 01 ALG', 'VT_ICNF', 'GFR', 'Algarve', 'Olhão'),
  ('GFR 09 NAC', 'VT_ICNF', 'GFR', 'Algarve', 'Lagos'),
  ('CNAF 40', 'VTEC', 'CNAF', 'Algarve', 'Castro Marim'),
  ('CNAF 56', 'VTEC', 'CNAF', 'Algarve', 'Olhão'),
  ('CNAF 57', 'VTEC', 'CNAF', 'Algarve', 'Lagos'),
  ('CNAF 40', 'VTEC', 'CNAF', 'Algarve', 'Vila Real de Santo António'),
  ('CNAF 56', 'VTEC', 'CNAF', 'Algarve', 'Olhão'),
  ('CNAF 57', 'VTEC', 'CNAF', 'Algarve', 'Olhão'),
  ('SF 01-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 02-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 03-182', 'ESF', 'ESF', 'Alto Alentejo', 'Castelo de Vide'),
  ('SF 04-182', 'ESF', 'ESF', 'Alto Alentejo', 'Gavião'),
  ('SF 05-182', 'ESF', 'ESF', 'Alto Alentejo', 'Alter do Chão'),
  ('SF 06-182', 'ESF', 'ESF', 'Alto Alentejo', 'Avis'),
  ('SF 07-182', 'ESF', 'ESF', 'Alto Alentejo', 'Crato'),
  ('SF 08-182', 'ESF', 'ESF', 'Alto Alentejo', 'Elvas'),
  ('SF 09-182', 'ESF', 'ESF', 'Alto Alentejo', 'Fronteira'),
  ('SF 10-182', 'ESF', 'ESF', 'Alto Alentejo', 'Marvão'),
  ('SF 17-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 11-182', 'ESF', 'ESF', 'Alto Alentejo', 'Nisa'),
  ('SF 12-182', 'ESF', 'ESF', 'Alto Alentejo', 'Sousel'),
  ('SF 16-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 13-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 15-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 14-182', 'ESF', 'ESF', 'Alto Alentejo', 'Ponte de Sor'),
  ('SF 15-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 16-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 17-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 18-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 19-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 20-182', 'ESF', 'ESF', 'Alto Alentejo', 'Portalegre'),
  ('SF 21-182', 'ESF', 'ESF', 'Alto Alentejo', 'Gavião'),
  ('VN ALE01', 'ESF', 'VN', 'Alto Alentejo', 'Portalegre'),
  ('VN ALE02', 'ESF', 'VN', 'Alto Alentejo', 'Portalegre'),
  ('VN ALE03', 'ESF', 'VN', 'Alto Alentejo', 'Portalegre'),
  ('ICNF 1701', 'ESF', 'VN', 'Alto Alentejo', 'Marvão'),
  ('ICNF 1702', 'ESF', 'VN', 'Alto Alentejo', 'Marvão'),
  ('ICNF 1703', 'ESF', 'VN', 'Alto Alentejo', 'Portalegre'),
  ('VN ALE04', 'ESF', 'VN', 'Alto Alentejo', 'Ponte de Sor'),
  ('MR 01 ICNF', 'MR', 'UNM_FSBF', 'Alto Alentejo', 'Portalegre'),
  ('MR 20 ICNF', 'MR', 'UNM_FSBF', 'Alto Alentejo', 'Portalegre'),
  ('PM 04 ICNF', 'PM', 'UNM_FSBF', 'Alto Alentejo', 'Portalegre'),
  ('TF 04 FSBF', 'TF', 'UNM_FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VFCI 04 FSBF', 'VFCI', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VLCI 23 FSBF', 'VLCI', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VLCI 15 FSBF', 'VLCI', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VLCI 16 FSBF', 'VLCI', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VLCI 18 FSBF', 'VLCI', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VAFR 21 FSBF', 'VLCI', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VAFR 23 FSBF', 'VLCI', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VAFR04_ALE', 'VT_ICNF', 'GFR', 'Alto Alentejo', 'Portalegre'),
  ('VAFR 02 ALE', 'VT_ICNF', 'GFR', 'Alto Alentejo', 'Portalegre'),
  ('VAFR 03 ALE', 'VT_ICNF', 'GFR', 'Alto Alentejo', 'Portalegre'),
  ('VAFR 04 ALE', 'VT_ICNF', 'GFR', 'Alto Alentejo', 'Portalegre'),
  ('VAFR 05 ALE', 'VT_ICNF', 'GFR', 'Alto Alentejo', 'Portalegre'),
  ('VASG 09 FSBF', 'VT_ICNF', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VGFR 01 ALE', 'VT_ICNF', 'GFR', 'Alto Alentejo', 'Portalegre'),
  ('VGFR 03 ALE', 'VT_ICNF', 'GFR', 'Alto Alentejo', 'Portalegre'),
  ('VAFR 27 FSBF', 'VT_ICNF', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('CNAF 49', 'VTEC', 'CNAF', 'Alto Alentejo', 'Portalegre'),
  ('VAOP 12 FSBF', 'VTEC_ICNF', 'FSBF', 'Alto Alentejo', 'Portalegre'),
  ('VTEC_ICNF_VN19', 'VTEC_ICNF', 'VN', 'Alto Alentejo', 'Portalegre'),
  ('VTEC_ICNF_VN33', 'VTEC_ICNF', 'VN', 'Alto Alentejo', 'Portalegre'),
  ('SF 03-111', 'ESF', 'ESF', 'Alto Minho', 'Viana do Castelo'),
  ('SF 04-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte de Lima'),
  ('SF 05-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte de Lima'),
  ('SF 06-111', 'ESF', 'ESF', 'Alto Minho', 'Monção'),
  ('SF 07-111', 'ESF', 'ESF', 'Alto Minho', 'Valença'),
  ('SF 08-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte de Lima'),
  ('SF 09-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte de Lima'),
  ('SF 10-111', 'ESF', 'ESF', 'Alto Minho', 'Arcos de Valdevez'),
  ('SF 11-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte da Barca'),
  ('SF 12-111', 'ESF', 'ESF', 'Alto Minho', 'Arcos de Valdevez'),
  ('SF 13-111', 'ESF', 'ESF', 'Alto Minho', 'Arcos de Valdevez'),
  ('SF 14-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte da Barca'),
  ('SF 15-111', 'ESF', 'ESF', 'Alto Minho', 'Arcos de Valdevez'),
  ('SF 16-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte de Lima'),
  ('SF 17-111', 'ESF', 'ESF', 'Alto Minho', 'Arcos de Valdevez'),
  ('SF 18-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte de Lima'),
  ('SF 19-111', 'ESF', 'ESF', 'Alto Minho', 'Valença'),
  ('SF 20-111', 'ESF', 'ESF', 'Alto Minho', 'Valença'),
  ('SF 21-111', 'ESF', 'ESF', 'Alto Minho', 'Viana do Castelo'),
  ('SF 22-111', 'ESF', 'ESF', 'Alto Minho', 'Melgaço'),
  ('SF 23-111', 'ESF', 'ESF', 'Alto Minho', 'Valença'),
  ('SF 24-111', 'ESF', 'ESF', 'Alto Minho', 'Melgaço'),
  ('SF 25-111', 'ESF', 'ESF', 'Alto Minho', 'Valença'),
  ('SF 26-111', 'ESF', 'ESF', 'Alto Minho', 'Ponte de Lima'),
  ('SF 27-111', 'ESF', 'ESF', 'Alto Minho', 'Valença'),
  ('SF 28-111', 'ESF', 'ESF', 'Alto Minho', 'Valença'),
  ('ICNF 1003', 'ESF', 'VN', 'Alto Minho', 'Ponte da Barca'),
  ('SF 01-111', 'VLCI', 'ESF', 'Alto Minho', 'Caminha'),
  ('VAFR 02 NRT', 'VT_ICNF', 'GFR', 'Alto Minho', 'Ponte de Lima'),
  ('VAFR 03 NRT', 'VT_ICNF', 'GFR', 'Alto Minho', 'Ponte de Lima'),
  ('VGFR 01 NRT', 'VT_ICNF', 'GFR', 'Alto Minho', 'Ponte de Lima'),
  ('VGFR 05 NRT', 'VT_ICNF', 'GFR', 'Alto Minho', 'Ponte de Lima'),
  ('CNAF 15', 'VTEC', 'CNAF', 'Alto Minho', 'Viana do Castelo'),
  ('CNAF 24', 'VTEC', 'CNAF', 'Alto Minho', 'Arcos de Valdevez'),
  ('CNAF 25', 'VTEC', 'CNAF', 'Alto Minho', 'Arcos de Valdevez'),
  ('CNAF 26', 'VTEC', 'CNAF', 'Alto Minho', 'Ponte da Barca'),
  ('CNAF 28', 'VTEC', 'CNAF', 'Alto Minho', 'Ponte da Barca'),
  ('CNAF 31', 'VTEC', 'CNAF', 'Alto Minho', 'Melgaço'),
  ('CNAF 32', 'VTEC', 'CNAF', 'Alto Minho', 'Melgaço'),
  ('CNAF 14', 'VTEC', 'CNAF', 'Alto Minho', 'Ponte de Lima'),
  ('CNAF 14A', 'VTEC', 'CNAF', 'Alto Minho', 'Ponte de Lima'),
  ('CNAF 14B', 'VTEC', 'CNAF', 'Alto Minho', 'Ponte de Lima'),
  ('CNAF 16', 'VTEC', 'CNAF', 'Alto Minho', 'Vila Nova de Cerveira'),
  ('CNAF 41', 'VTEC', 'CNAF', 'Alto Minho', 'Viana do Castelo'),
  ('CNAF 51', 'VTEC', 'CNAF', 'Alto Minho', 'Melgaço'),
  ('SF 02-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('SF 43-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('SF 04-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 05-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 06-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 07-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 08-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 12-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 14-115', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('SF 15-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('SF 17-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 18-115', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('SF 18-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('SF 19-115', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('SF 20-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('SF 22-115', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('SF 22-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('SF 25-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('SF 27-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 28-115', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('SF 30-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 31-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 32-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Valpaços'),
  ('SF 36-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 37-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 38-115', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('SF 38-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 39-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('SF 40-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 41-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Valpaços'),
  ('SF 42-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Valpaços'),
  ('SF 43-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('SF 45-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('SF 47-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('SF 48-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('SF 50-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 51-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 52-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('SF 58-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Chaves'),
  ('ESF 11-118', 'ESF', 'ESF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('ICNF 1005', 'ESF', 'VN', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('MR 14 ICNF', 'MR', 'UNM_FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('MR 17 ICNF', 'MR', 'UNM_FSBF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('MR 21 ICNF', 'MR', 'UNM_FSBF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('PM 06 ICNF', 'PM', 'UNM_FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('PM_ICNF_06', 'VALE', 'UNM_FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VFCI 01 FSBF', 'VFCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VLCI 01 FSBF', 'VFCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VLCI 01 FSBF', 'VLCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VLCI 05 FSBF', 'VLCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VLCI 17 FSBF', 'VLCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VLCI 20 FSBF', 'VLCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VAFR 18 FSBF', 'VLCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VAFR 19 FSBF', 'VLCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VLCI 23 FSBF', 'VLCI', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VAFR06_NRT', 'VT_ICNF', 'GFR', 'Alto Tâmega e Barroso', 'Chaves'),
  ('VAFR11_NRT', 'VT_ICNF', 'GFR', 'Alto Tâmega e Barroso', 'Chaves'),
  ('VAFR 05 NRT', 'VT_ICNF', 'GFR', 'Alto Tâmega e Barroso', 'Chaves'),
  ('VAFR 10 NRT', 'VT_ICNF', 'GFR', 'Alto Tâmega e Barroso', 'Chaves'),
  ('VAFR 25 FSBF', 'VT_ICNF', 'GFR', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VASG 04 FSBF', 'VT_ICNF', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VGFR 03 NRT', 'VT_ICNF', 'GFR', 'Alto Tâmega e Barroso', 'Chaves'),
  ('VGFR 09 NRT', 'VT_ICNF', 'GFR', 'Alto Tâmega e Barroso', 'Chaves'),
  ('VAFR 17 FSBF', 'VT_ICNF', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VAFR 26 FSBF', 'VT_ICNF', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('CNAF 21', 'VTEC', 'CNAF', 'Alto Tâmega e Barroso', 'Ribeira de Pena'),
  ('CNAF 29', 'VTEC', 'CNAF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('CNAF 30', 'VTEC', 'CNAF', 'Alto Tâmega e Barroso', 'Montalegre'),
  ('CNAF 17', 'VTEC', 'CNAF', 'Alto Tâmega e Barroso', 'Boticas'),
  ('CNAF 43', 'VTEC', 'CNAF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('VAOP 13 FSBF', 'VTEC_ICNF', 'FSBF', 'Alto Tâmega e Barroso', 'Vila Pouca de Aguiar'),
  ('SF 01-113', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Trofa'),
  ('SF 01-114', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Gondomar'),
  ('SF 02-114', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Gondomar'),
  ('SF 02-116', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Arouca'),
  ('SF 03-114', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Gondomar'),
  ('SF 03-116', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Arouca'),
  ('SF 04-114', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Gondomar'),
  ('SF 04-116', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Arouca'),
  ('SF 05-116', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Arouca'),
  ('SF 06-113', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Trofa'),
  ('SF 06-116', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Arouca'),
  ('SF 07-113', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Trofa'),
  ('SF 07-116', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Vale de Cambra'),
  ('SF 08-113', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Trofa'),
  ('SF 15-113', 'ESF', 'ESF', 'Área Metropolitana do Porto', 'Trofa'),
  ('VGFR 02 NRT', 'VT_ICNF', 'GFR', 'Área Metropolitana do Porto', 'Valongo'),
  ('VGFR 07 NRT', 'VT_ICNF', 'GFR', 'Área Metropolitana do Porto', 'Arouca'),
  ('VGFR 10 NRT', 'VT_ICNF', 'GFR', 'Área Metropolitana do Porto', 'Porto'),
  ('SF 02-113', 'ESF', 'ESF', 'Ave', 'Vieira do Minho'),
  ('SF 04-113', 'ESF', 'ESF', 'Ave', 'Fafe'),
  ('SF 12-113', 'ESF', 'ESF', 'Ave', 'Guimarães'),
  ('SF 11-113', 'ESF', 'ESF', 'Ave', 'Guimarães'),
  ('SF 09-113', 'ESF', 'ESF', 'Ave', 'Vieira do Minho'),
  ('SF 10-113', 'ESF', 'ESF', 'Ave', 'Vieira do Minho'),
  ('SF 11-113', 'ESF', 'ESF', 'Ave', 'Guimarães'),
  ('SF 12-113', 'ESF', 'ESF', 'Ave', 'Guimarães'),
  ('SF 13-113', 'ESF', 'ESF', 'Ave', 'Guimarães'),
  ('SF 13-115', 'ESF', 'ESF', 'Ave', 'Mondim de Basto'),
  ('SF 14-113', 'ESF', 'ESF', 'Ave', 'Vieira do Minho'),
  ('SF 16-115', 'ESF', 'ESF', 'Ave', 'Cabeceiras de Basto'),
  ('SF 24-115', 'ESF', 'ESF', 'Ave', 'Cabeceiras de Basto'),
  ('SF 25-115', 'ESF', 'ESF', 'Ave', 'Mondim de Basto'),
  ('SF 27-115', 'ESF', 'ESF', 'Ave', 'Mondim de Basto'),
  ('SF 29-115', 'ESF', 'ESF', 'Ave', 'Cabeceiras de Basto'),
  ('SF 30-115', 'ESF', 'ESF', 'Ave', 'Mondim de Basto'),
  ('SF 42-115', 'ESF', 'ESF', 'Ave', 'Cabeceiras de Basto'),
  ('SF 47-115', 'ESF', 'ESF', 'Ave', 'Cabeceiras de Basto'),
  ('ESF 13-113', 'ESF', 'ESF', 'Ave', 'Guimarães'),
  ('MR 02 ICNF', 'MR', 'UNM_FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('MR 04 ICNF', 'MR', 'UNM_FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('MR 09 ICNF', 'MR', 'UNM_FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('MR_ICNF 200', 'MR', 'UNM_FSBF', 'Ave', 'Guimarães'),
  ('MR ICNF 01', 'MR', 'UNM_FSBF', 'Ave', 'Guimarães'),
  ('PM 01 ICNF', 'PM', 'UNM_FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VFCI 02 FSBF', 'VFCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VLCI 02 FSBF', 'VLCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VLCI 02 FSBF', 'VLCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VLCI 03 FSBF', 'VLCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VLCI 04 FSBF', 'VLCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VLCI 06 FSBF', 'VLCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VLCI 19 FSBF', 'VLCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VAFR 20 FSBF', 'VLCI', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VASG 01 NRT', 'VT_ICNF', 'GFR', 'Ave', 'Cabeceiras de Basto'),
  ('VASG 02 FSBF', 'VT_ICNF', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('VASG 03 FSBF', 'VT_ICNF', 'FSBF', 'Ave', 'Cabeceiras de Basto'),
  ('CNAF 19', 'VTEC', 'CNAF', 'Ave', 'Cabeceiras de Basto'),
  ('CNAF 20', 'VTEC', 'CNAF', 'Ave', 'Mondim de Basto'),
  ('CNAF 44', 'VTEC', 'CNAF', 'Ave', 'Mondim de Basto'),
  ('SF 01-184', 'ESF', 'ESF', 'Baixo Alentejo', 'Ourique'),
  ('SF 02-184', 'ESF', 'ESF', 'Baixo Alentejo', 'Almodôvar'),
  ('SF 03-184', 'ESF', 'ESF', 'Baixo Alentejo', 'Barrancos'),
  ('SF 04-184', 'ESF', 'ESF', 'Baixo Alentejo', 'Moura'),
  ('SF 05-184', 'ESF', 'ESF', 'Baixo Alentejo', 'Vidigueira'),
  ('ICNF 2100', 'ESF', 'VN', 'Baixo Alentejo', 'Mértola'),
  ('ICNF 2101', 'ESF', 'VN', 'Baixo Alentejo', 'Mértola'),
  ('VN ALE06', 'ESF', 'VN', 'Baixo Alentejo', 'Beja'),
  ('VN ALE07', 'ESF', 'VN', 'Baixo Alentejo', 'Mértola'),
  ('VN ALE08', 'ESF', 'VN', 'Baixo Alentejo', 'Mértola'),
  ('VN ALE09', 'ESF', 'VN', 'Baixo Alentejo', 'Mértola'),
  ('CNAF 52', 'VTEC', 'CNAF', 'Baixo Alentejo', 'Mértola'),
  ('SF 01-166', 'ESF', 'ESF', 'Beira Baixa', 'Proença-a-Nova'),
  ('SF 01-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 02-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 03-166', 'ESF', 'ESF', 'Beira Baixa', 'Vila de Rei'),
  ('SF 03-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 04-166', 'ESF', 'ESF', 'Beira Baixa', 'Sertã'),
  ('SF 04-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 05-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 07-166', 'ESF', 'ESF', 'Beira Baixa', 'Proença-a-Nova'),
  ('SF 07-169', 'ESF', 'ESF', 'Beira Baixa', 'Proença-a-Nova'),
  ('SF 08-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 09-166', 'ESF', 'ESF', 'Beira Baixa', 'Sertã'),
  ('SF 09-169', 'ESF', 'ESF', 'Beira Baixa', 'Penamacor'),
  ('SF 10-166', 'ESF', 'ESF', 'Beira Baixa', 'Oleiros'),
  ('SF 10-169', 'ESF', 'ESF', 'Beira Baixa', 'Idanha-a-Nova'),
  ('SF 11-166', 'ESF', 'ESF', 'Beira Baixa', 'Oleiros'),
  ('SF 11-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 12-166', 'ESF', 'ESF', 'Beira Baixa', 'Idanha-a-Nova'),
  ('SF 12-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 13-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 14-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 15-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('SF 16-169', 'ESF', 'ESF', 'Beira Baixa', 'Castelo Branco'),
  ('VN 16', 'ESF', 'VN', 'Beira Baixa', 'Castelo Branco'),
  ('ICNF 1500', 'ESF', 'VN', 'Beira Baixa', 'Castelo Branco'),
  ('ICNF 1501', 'ESF', 'VN', 'Beira Baixa', 'Castelo Branco'),
  ('ICNF 2600', 'ESF', 'VN', 'Beira Baixa', 'Penamacor'),
  ('ICNF 2602', 'ESF', 'VN', 'Beira Baixa', 'Penamacor'),
  ('ICNF Malcata', 'ESF', 'VN', 'Beira Baixa', 'Penamacor'),
  ('MR_ICNF 329', 'MR', 'UNM_FSBF', 'Beira Baixa', 'Proença-a-Nova'),
  ('MR ICNF 03', 'MR', 'UNM_FSBF', 'Beira Baixa', 'Proença-a-Nova'),
  ('PM_ICNF_10', 'VALE', 'UNM_FSBF', 'Beira Baixa', 'Proença-a-Nova'),
  ('VLCI 07 FSBF', 'VLCI', 'FSBF', 'Beira Baixa', 'Proença-a-Nova'),
  ('VAFR 05 FSBF', 'VLCI', 'FSBF', 'Beira Baixa', 'Proença-a-Nova'),
  ('VAFR 14 FSBF', 'VLCI', 'FSBF', 'Beira Baixa', 'Proença-a-Nova'),
  ('VASG05_CNT', 'VT_ICNF', 'GFR', 'Beira Baixa', 'Castelo Branco'),
  ('VAFR 05 CNT', 'VT_ICNF', 'GFR', 'Beira Baixa', 'Castelo Branco'),
  ('VAFR 07 CNT', 'VT_ICNF', 'GFR', 'Beira Baixa', 'Castelo Branco'),
  ('VAFR 08 CNT', 'VT_ICNF', 'GFR', 'Beira Baixa', 'Castelo Branco'),
  ('VASG 05 FSBF', 'VT_ICNF', 'FSBF', 'Beira Baixa', 'Proença-a-Nova'),
  ('VGFR 08 CNT', 'VT_ICNF', 'GFR', 'Beira Baixa', 'Castelo Branco'),
  ('CNAF 36', 'VTEC', 'CNAF', 'Beira Baixa', 'Idanha-a-Nova'),
  ('CNAF 37', 'VTEC', 'CNAF', 'Beira Baixa', 'Penamacor'),
  ('VGFR 01 CNT', 'VTEC_ICNF', 'GFR', 'Beira Baixa', 'Castelo Branco'),
  ('SF 01-167', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Gouveia'),
  ('SF 01-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Fundão'),
  ('SF 02-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Celorico da Beira'),
  ('SF 03-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('SF 04-167', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Fornos de Algodres'),
  ('SF 26-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 04-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Celorico da Beira'),
  ('SF 27-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 05-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('SF 05-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 06-167', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Gouveia'),
  ('SF 06-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Figueira de Castelo Rodrigo'),
  ('SF 07-167', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Gouveia'),
  ('SF 07-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 07-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Fundão'),
  ('SF 08-167', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Seia'),
  ('SF 08-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('SF 09-167', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Seia'),
  ('SF 09-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('SF 09-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 10-167', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Seia'),
  ('SF 10-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Almeida'),
  ('SF 10-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 11-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Trancoso'),
  ('SF 11-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Fundão'),
  ('SF 12-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 13-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('SF 13-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 14-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Trancoso'),
  ('SF 14-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 15-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('SF 15-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 16-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('SF 16-16A', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Covilhã'),
  ('SF 17-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Mêda'),
  ('SF 18-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('SF 19-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('SF 20-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Celorico da Beira'),
  ('SF 21-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 22-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Almeida'),
  ('SF 23-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Pinhel'),
  ('SF 24-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 25-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 26-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 27-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 28-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 29-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Trancoso'),
  ('VN 08', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('VN 08.01', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('VN 14', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Seia'),
  ('VN 28', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('VN 28.1', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('ESF 28-168', 'ESF', 'ESF', 'Beiras e Serra da Estrela', 'Belmonte'),
  ('ICNF 1300', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Figueira de Castelo Rodrigo'),
  ('ICNF 1400', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Seia'),
  ('ICNF 1402', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('ICNF 1403', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Seia'),
  ('ICNF 1404', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('ICNF 1405', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('ICNF 2601', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Sabugal'),
  ('ICNF Tejo Internacional', 'ESF', 'VN', 'Beiras e Serra da Estrela', 'Fundão'),
  ('MR 03 ICNF', 'MR', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('MR 07 ICNF', 'MR', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('MR 11 ICNF', 'MR', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('MR 19 ICNF', 'MR', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('MR 22 ICNF', 'MR', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('MR_ICNF 322', 'MR', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Trancoso'),
  ('MR ICNF 02', 'MR', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Trancoso'),
  ('PM 02 ICNF', 'PM', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('TRATOR_FLORESTAL', 'TF', 'UNM_FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VFCI 03 FSBF', 'VFCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VLCI 08 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VLCI 09 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 09 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 03 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 04 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 07 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 08 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 13 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 15 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VLCI 21 FSBF', 'VLCI', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 01 CNT', 'VT_ICNF', 'GFR', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VASG 01 CNT', 'VT_ICNF', 'GFR', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VAFR 04 CNT', 'VT_ICNF', 'GFR', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VASG 06 FSBF', 'VT_ICNF', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VASG 07 FSBF', 'VT_ICNF', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VGFR 04 CNT', 'VT_ICNF', 'GFR', 'Beiras e Serra da Estrela', 'Guarda'),
  ('VGFR 09 CNT', 'VT_ICNF', 'GFR', 'Beiras e Serra da Estrela', 'Guarda'),
  ('CNAF 11', 'VTEC', 'CNAF', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('CNAF 10', 'VTEC', 'CNAF', 'Beiras e Serra da Estrela', 'Manteigas'),
  ('VAOP 11 FSBF', 'VTEC_ICNF', 'FSBF', 'Beiras e Serra da Estrela', 'Guarda'),
  ('SF 01-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 02-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 03-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 04-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 05-112', 'ESF', 'ESF', 'Cávado', 'Terras de Bouro'),
  ('SF 05-113', 'ESF', 'ESF', 'Cávado', 'Terras de Bouro'),
  ('SF 06-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 07-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 08-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 09-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('SF 10-112', 'ESF', 'ESF', 'Cávado', 'Braga'),
  ('ICNF 1004', 'ESF', 'VN', 'Cávado', 'Terras de Bouro'),
  ('ICNF 1006', 'ESF', 'VN', 'Cávado', 'Braga'),
  ('ICNF 1007', 'ESF', 'VN', 'Cávado', 'Braga'),
  ('VAFR 04 NRT', 'VT_ICNF', 'GFR', 'Cávado', 'Braga'),
  ('VGFR 06 NRT', 'VT_ICNF', 'GFR', 'Cávado', 'Braga'),
  ('CNAF 23', 'VTEC', 'CNAF', 'Cávado', 'Terras de Bouro'),
  ('CNAF 27', 'VTEC', 'CNAF', 'Cávado', 'Terras de Bouro'),
  ('CNAF 50', 'VTEC', 'CNAF', 'Cávado', 'Terras de Bouro'),
  ('SF 01-117', 'ESF', 'ESF', 'Douro', 'Moimenta da Beira'),
  ('SF 03-117', 'ESF', 'ESF', 'Douro', 'Murça'),
  ('SF 04-117', 'ESF', 'ESF', 'Douro', 'Penedono'),
  ('SF 16-117', 'ESF', 'ESF', 'Douro', 'São João da Pesqueira'),
  ('SF 06-117', 'ESF', 'ESF', 'Douro', 'Lamego'),
  ('SF 08-117', 'ESF', 'ESF', 'Douro', 'Vila Real'),
  ('SF 09-117', 'ESF', 'ESF', 'Douro', 'Lamego'),
  ('SF 10-117', 'ESF', 'ESF', 'Douro', 'Murça'),
  ('SF 11-117', 'ESF', 'ESF', 'Douro', 'Vila Real'),
  ('SF 13-117', 'ESF', 'ESF', 'Douro', 'Tarouca'),
  ('SF 14-117', 'ESF', 'ESF', 'Douro', 'Sabrosa'),
  ('SF 15-117', 'ESF', 'ESF', 'Douro', 'Freixo de Espada �  Cinta'),
  ('SF 17-117', 'ESF', 'ESF', 'Douro', 'Sernancelhe'),
  ('SF 18-117', 'ESF', 'ESF', 'Douro', 'Moimenta da Beira'),
  ('SF 19-117', 'ESF', 'ESF', 'Douro', 'Torre de Moncorvo'),
  ('SF 20-117', 'ESF', 'ESF', 'Douro', 'Vila Real'),
  ('SF 21-117', 'ESF', 'ESF', 'Douro', 'Murça'),
  ('SF 26-118', 'ESF', 'ESF', 'Douro', 'Murça'),
  ('SF 32-115', 'ESF', 'ESF', 'Douro', 'Vila Real'),
  ('ICNF 1200', 'ESF', 'VN', 'Douro', 'Vila Real'),
  ('ICNF 1201', 'ESF', 'VN', 'Douro', 'Vila Real'),
  ('VAFR08_NRT', 'VT_ICNF', 'GFR', 'Douro', 'Vila Real'),
  ('VAFR 07 NRT', 'VT_ICNF', 'GFR', 'Douro', 'Vila Real'),
  ('VGFR 04 NRT', 'VT_ICNF', 'GFR', 'Douro', 'Vila Real'),
  ('CNAF 42', 'VTEC', 'CNAF', 'Douro', 'Vila Real'),
  ('SF 01-171', 'ESF', 'ESF', 'Grande Lisboa', 'Mafra'),
  ('SF 02-171', 'ESF', 'ESF', 'Grande Lisboa', 'Mafra'),
  ('SF 04-171', 'ESF', 'ESF', 'Grande Lisboa', 'Cascais'),
  ('SF 05-171', 'ESF', 'ESF', 'Grande Lisboa', 'Loures'),
  ('SF 06-171', 'ESF', 'ESF', 'Grande Lisboa', 'Sintra'),
  ('VN 18.00', 'ESF', 'VN', 'Grande Lisboa', 'Sintra'),
  ('ESF 03-171', 'ESF', 'ESF', 'Grande Lisboa', 'Sintra'),
  ('ICNF 1800', 'ESF', 'VN', 'Grande Lisboa', 'Sintra'),
  ('MR ICNF 01', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 02', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 03', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 04', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 05', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 06', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 07', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 08', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 09', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('MR ICNF 10', 'MR', 'UNM_FSBF', 'Grande Lisboa', 'Lisboa'),
  ('VAFR 01 FSBF', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VAFR 01 LVT', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Sintra'),
  ('VAFR 02 FSBF', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VAFR 04 LVT', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Sintra'),
  ('VASG 01 FSBF', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VGFR 05 LVT', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Sintra'),
  ('VT_ICNF_01.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_02,01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_03.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_04.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_05.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_06.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_07.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_08.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_09.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_10.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_11.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_12.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_13.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_14.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_15.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_16.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_17.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('VT_ICNF_18.01', 'VT_ICNF', 'GFR', 'Grande Lisboa', 'Lisboa'),
  ('SF 01-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Coruche'),
  ('SF 02-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Chamusca'),
  ('SF 03-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Rio Maior'),
  ('SF 04-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('SF 05-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Azambuja'),
  ('SF 06-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('SF 07-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('SF 08-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('SF 06-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('SF 08-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('SF 07-185', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('ESF 03-16B', 'ESF', 'ESF', 'Lezíria do Tejo', 'Azambuja'),
  ('ESF 13-16C', 'ESF', 'ESF', 'Lezíria do Tejo', 'Santarém'),
  ('ICNF 1601', 'ESF', 'VN', 'Lezíria do Tejo', 'Rio Maior'),
  ('ICNF 1602', 'ESF', 'VN', 'Lezíria do Tejo', 'Rio Maior'),
  ('ICNF 1603', 'ESF', 'VN', 'Lezíria do Tejo', 'Rio Maior'),
  ('ICNF 1604', 'ESF', 'VN', 'Lezíria do Tejo', 'Rio Maior'),
  ('MR 16 ICNF', 'MR', 'UNM_FSBF', 'Lezíria do Tejo', 'Santarém'),
  ('PM 07 ICNF', 'PM', 'UNM_FSBF', 'Lezíria do Tejo', 'Santarém'),
  ('VLCI 11 FSBF', 'VLCI', 'FSBF', 'Lezíria do Tejo', 'Santarém'),
  ('VLCI 12 FSBF', 'VLCI', 'FSBF', 'Lezíria do Tejo', 'Santarém'),
  ('VAFR 22 FSBF', 'VLCI', 'FSBF', 'Lezíria do Tejo', 'Santarém'),
  ('VAFR07_LVT', 'VT_ICNF', 'GFR', 'Lezíria do Tejo', 'Santarém'),
  ('VAFR08_LVT', 'VT_ICNF', 'GFR', 'Lezíria do Tejo', 'Santarém'),
  ('VAFR10_LVT', 'VT_ICNF', 'GFR', 'Lezíria do Tejo', 'Rio Maior'),
  ('VAFR 05 LVT', 'VT_ICNF', 'GFR', 'Lezíria do Tejo', 'Santarém'),
  ('VAFR 06 LVT', 'VT_ICNF', 'GFR', 'Lezíria do Tejo', 'Rio Maior'),
  ('VAFR 09 LVT', 'VT_ICNF', 'GFR', 'Lezíria do Tejo', 'Santarém'),
  ('VASG 08 FSBF', 'VT_ICNF', 'FSBF', 'Lezíria do Tejo', 'Santarém'),
  ('VGFR 04 LVT', 'VT_ICNF', 'GFR', 'Lezíria do Tejo', 'Santarém'),
  ('CNAF 45', 'VTEC', 'CNAF', 'Lezíria do Tejo', 'Salvaterra de Magos'),
  ('CNAF 48', 'VTEC', 'CNAF', 'Lezíria do Tejo', 'Santarém'),
  ('CNAF 38', 'VTEC', 'CNAF', 'Lezíria do Tejo', 'Azambuja'),
  ('VAOP 14 FSBF', 'VTEC_ICNF', 'FSBF', 'Lezíria do Tejo', 'Santarém'),
  ('SF 01-16C', 'ESF', 'ESF', 'Médio Tejo', 'Abrantes'),
  ('SF 03-16C', 'ESF', 'ESF', 'Médio Tejo', 'Abrantes'),
  ('SF 04-16C', 'ESF', 'ESF', 'Médio Tejo', 'Abrantes'),
  ('SF 05-16C', 'ESF', 'ESF', 'Médio Tejo', 'Alcanena'),
  ('SF 07-16C', 'ESF', 'ESF', 'Médio Tejo', 'Ferreira do Zêzere'),
  ('SF 08-16C', 'ESF', 'ESF', 'Médio Tejo', 'Ferreira do Zêzere'),
  ('SF 09-16C', 'ESF', 'ESF', 'Médio Tejo', 'Constância'),
  ('SF 22-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 11-16C', 'ESF', 'ESF', 'Médio Tejo', 'Alcanena'),
  ('SF 21-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 12-16C', 'ESF', 'ESF', 'Médio Tejo', 'Sardoal'),
  ('SF 13-166', 'ESF', 'ESF', 'Médio Tejo', 'Ferreira do Zêzere'),
  ('SF 20-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 14-16C', 'ESF', 'ESF', 'Médio Tejo', 'Mação'),
  ('SF 15-16C', 'ESF', 'ESF', 'Médio Tejo', 'Mação'),
  ('SF 16-16C', 'ESF', 'ESF', 'Médio Tejo', 'Mação'),
  ('SF 19-16C', 'ESF', 'ESF', 'Médio Tejo', 'Abrantes'),
  ('SF 20-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 21-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 22-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 23-16C', 'ESF', 'ESF', 'Médio Tejo', 'Ourém'),
  ('SF 24-16C', 'ESF', 'ESF', 'Médio Tejo', 'Abrantes'),
  ('SF 25-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 26-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 27-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('SF 28-16C', 'ESF', 'ESF', 'Médio Tejo', 'Ferreira do Zêzere'),
  ('SF 29-16C', 'ESF', 'ESF', 'Médio Tejo', 'Abrantes'),
  ('ESF 06-166', 'ESF', 'ESF', 'Médio Tejo', 'Mação'),
  ('ESF 08-166', 'ESF', 'ESF', 'Médio Tejo', 'Mação'),
  ('ESF 10-16C', 'ESF', 'ESF', 'Médio Tejo', 'Tomar'),
  ('ICNF 2800', 'ESF', 'VN', 'Médio Tejo', 'Torres Novas'),
  ('VGFR 02 LVT', 'VT_ICNF', 'GFR', 'Médio Tejo', 'Ourém'),
  ('SF 02-16B', 'ESF', 'ESF', 'Oeste', 'Alcobaça'),
  ('SF 03-16B', 'ESF', 'ESF', 'Oeste', 'Cadaval'),
  ('SF 08-16B', 'ESF', 'ESF', 'Oeste', 'Caldas da Rainha'),
  ('SF 09-16B', 'ESF', 'ESF', 'Oeste', 'Caldas da Rainha'),
  ('SF 05-16B', 'ESF', 'ESF', 'Oeste', 'Nazaré'),
  ('SF 06-16B', 'ESF', 'ESF', 'Oeste', 'Peniche'),
  ('SF 07-16B', 'ESF', 'ESF', 'Oeste', 'Torres Vedras'),
  ('SF 08-163', 'ESF', 'ESF', 'Oeste', 'Alcobaça'),
  ('SF 10-16B', 'ESF', 'ESF', 'Oeste', 'Caldas da Rainha'),
  ('SF 11-16B', 'ESF', 'ESF', 'Oeste', 'Torres Vedras'),
  ('SF 04-16B', 'ESF', 'ESF', 'Oeste', 'Alenquer'),
  ('SF-08-16B', 'ESF', 'ESF', 'Oeste', 'Caldas da Rainha'),
  ('SF-09-16B', 'ESF', 'ESF', 'Oeste', 'Caldas da Rainha'),
  ('SF-10-16B', 'ESF', 'ESF', 'Oeste', 'Caldas da Rainha'),
  ('ESF 01-16B', 'ESF', 'ESF', 'Oeste', 'Cadaval'),
  ('MR 18 ICNF', 'MR', 'UNM_FSBF', 'Oeste', 'Nazaré'),
  ('CNAF 12', 'VTEC', 'CNAF', 'Oeste', 'Nazaré'),
  ('BRG 01-16B', 'VTEC', 'ESF', 'Oeste', 'Caldas da Rainha'),
  ('VN 19.03', 'ESF', 'VN', 'Península de Setúbal', 'Setúbal'),
  ('VN 30.00', 'ESF', 'VN', 'Península de Setúbal', 'Setúbal'),
  ('VN 30.01', 'ESF', 'VN', 'Península de Setúbal', 'Setúbal'),
  ('VN 36.00', 'ESF', 'VN', 'Península de Setúbal', 'Setúbal'),
  ('ESF 19-03', 'ESF', 'ESF', 'Península de Setúbal', 'Palmela'),
  ('ESF 30-00', 'ESF', 'ESF', 'Península de Setúbal', 'Sesimbra'),
  ('ESF 30-01', 'ESF', 'ESF', 'Península de Setúbal', 'Montijo'),
  ('ESF 36-00', 'ESF', 'ESF', 'Península de Setúbal', 'Almada'),
  ('ICNF 1901', 'ESF', 'VN', 'Península de Setúbal', 'Setúbal'),
  ('ICNF 1903', 'ESF', 'VN', 'Península de Setúbal', 'Setúbal'),
  ('ICNF 2900', 'ESF', 'VN', 'Península de Setúbal', 'Alcochete'),
  ('ICNF 3001', 'ESF', 'VN', 'Península de Setúbal', 'Setúbal'),
  ('ICNF 3600', 'ESF', 'VN', 'Península de Setúbal', 'Almada'),
  ('VAFR06_LVT', 'VT_ICNF', 'GFR', 'Península de Setúbal', 'Alcochete'),
  ('VAFR 02 LVT', 'VT_ICNF', 'GFR', 'Península de Setúbal', 'Alcochete'),
  ('VAFR 03 LVT', 'VT_ICNF', 'GFR', 'Península de Setúbal', 'Alcochete'),
  ('CNAF 46', 'VTEC', 'CNAF', 'Península de Setúbal', 'Almada'),
  ('CNAF 47', 'VTEC', 'CNAF', 'Península de Setúbal', 'Setúbal'),
  ('SF 01-161', 'ESF', 'ESF', 'Região de Aveiro', 'Albergaria-a-Velha'),
  ('SF 02-161', 'ESF', 'ESF', 'Região de Aveiro', 'Sever do Vouga'),
  ('SF 03-161', 'ESF', 'ESF', 'Região de Aveiro', 'Albergaria-a-Velha'),
  ('SF 04-161', 'ESF', 'ESF', 'Região de Aveiro', '�gueda'),
  ('VN 06', 'ESF', 'VN', 'Região de Aveiro', 'Aveiro'),
  ('VN 06.1', 'ESF', 'VN', 'Região de Aveiro', 'Aveiro'),
  ('ESF 32-164', 'ESF', 'ESF', 'Região de Aveiro', 'Aveiro'),
  ('ICNF 2500', 'ESF', 'VN', 'Região de Aveiro', 'Aveiro'),
  ('SF 05-161', 'ESF', 'ESF', 'Região de Aveiro', 'Anadia'),
  ('MR 15 ICNF', 'MR', 'UNM_FSBF', 'Região de Aveiro', 'Albergaria-a-Velha'),
  ('MR_ICNF 801', 'MR', 'UNM_FSBF', 'Região de Aveiro', '�gueda'),
  ('PM 05 ICNF', 'PM', 'UNM_FSBF', 'Região de Aveiro', 'Albergaria-a-Velha'),
  ('PM_ICNF_05', 'VALE', 'UNM_FSBF', 'Região de Aveiro', 'Albergaria-a-Velha'),
  ('VASG04_CNT', 'VT_ICNF', 'GFR', 'Região de Aveiro', 'Aveiro'),
  ('VGFR 05 CNT', 'VT_ICNF', 'GFR', 'Região de Aveiro', 'Aveiro'),
  ('SF 01-162', 'ESF', 'ESF', 'Região de Coimbra', 'Penacova'),
  ('SF 01-164', 'ESF', 'ESF', 'Região de Coimbra', 'Oliveira do Hospital'),
  ('SF 02-162', 'ESF', 'ESF', 'Região de Coimbra', 'Figueira da Foz'),
  ('SF 03-162', 'ESF', 'ESF', 'Região de Coimbra', 'Mira'),
  ('SF 03-164', 'ESF', 'ESF', 'Região de Coimbra', 'Góis'),
  ('SF 04-162', 'ESF', 'ESF', 'Região de Coimbra', 'Soure'),
  ('SF 04-164', 'ESF', 'ESF', 'Região de Coimbra', 'Oliveira do Hospital'),
  ('SF 34-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('SF 34-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('SF 05-162', 'ESF', 'ESF', 'Região de Coimbra', 'Figueira da Foz'),
  ('SF 06-162', 'ESF', 'ESF', 'Região de Coimbra', 'Cantanhede'),
  ('SF 07-161', 'ESF', 'ESF', 'Região de Coimbra', 'Mealhada'),
  ('SF 07-162', 'ESF', 'ESF', 'Região de Coimbra', 'Oliveira do Hospital'),
  ('SF 07-164', 'ESF', 'ESF', 'Região de Coimbra', 'Lousã'),
  ('SF 07-165', 'ESF', 'ESF', 'Região de Coimbra', 'Mortágua'),
  ('SF 09-164', 'ESF', 'ESF', 'Região de Coimbra', 'Pampilhosa da Serra'),
  ('SF 30-164', 'ESF', 'ESF', 'Região de Coimbra', 'Vila Nova de Poiares'),
  ('SF 10-162', 'ESF', 'ESF', 'Região de Coimbra', 'Montemor-o-Velho'),
  ('SF 10-164', 'ESF', 'ESF', 'Região de Coimbra', 'Góis'),
  ('SF 11-162', 'ESF', 'ESF', 'Região de Coimbra', 'Cantanhede'),
  ('SF 12-162', 'ESF', 'ESF', 'Região de Coimbra', 'Penacova'),
  ('SF 13-164', 'ESF', 'ESF', 'Região de Coimbra', 'Lousã'),
  ('SF 14-164', 'ESF', 'ESF', 'Região de Coimbra', 'Tábua'),
  ('SF 16-164', 'ESF', 'ESF', 'Região de Coimbra', 'Arganil'),
  ('SF 18-164', 'ESF', 'ESF', 'Região de Coimbra', 'Oliveira do Hospital'),
  ('SF 19-164', 'ESF', 'ESF', 'Região de Coimbra', 'Lousã'),
  ('SF 20-164', 'ESF', 'ESF', 'Região de Coimbra', 'Penela'),
  ('SF 25-164', 'ESF', 'ESF', 'Região de Coimbra', 'Pampilhosa da Serra'),
  ('SF 26-164', 'ESF', 'ESF', 'Região de Coimbra', 'Góis'),
  ('SF 27-164', 'ESF', 'ESF', 'Região de Coimbra', 'Miranda do Corvo'),
  ('SF 28-164', 'ESF', 'ESF', 'Região de Coimbra', 'Oliveira do Hospital'),
  ('SF 31-164', 'ESF', 'ESF', 'Região de Coimbra', 'Lousã'),
  ('SF 32-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('SF 33-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('SF 35-164', 'ESF', 'ESF', 'Região de Coimbra', 'Miranda do Corvo'),
  ('SF 37-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('SF 37-165', 'ESF', 'ESF', 'Região de Coimbra', 'Mortágua'),
  ('SF 39-164', 'ESF', 'ESF', 'Região de Coimbra', 'Pampilhosa da Serra'),
  ('SF 13-162', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('VN 22', 'ESF', 'VN', 'Região de Coimbra', 'Coimbra'),
  ('VN 22.1', 'ESF', 'VN', 'Região de Coimbra', 'Coimbra'),
  ('ESF 08-162', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('ESF 09-162', 'ESF', 'ESF', 'Região de Coimbra', 'Condeixa-a-Nova'),
  ('ESF 21-164', 'ESF', 'ESF', 'Região de Coimbra', 'Miranda do Corvo'),
  ('ESF 29-164', 'ESF', 'ESF', 'Região de Coimbra', 'Vila Nova de Poiares'),
  ('ESF 33-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('SF 38-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('ICNF 2700', 'ESF', 'VN', 'Região de Coimbra', 'Coimbra'),
  ('SF 06-161', 'ESF', 'ESF', 'Região de Coimbra', 'Mealhada'),
  ('SF 36-164', 'ESF', 'ESF', 'Região de Coimbra', 'Coimbra'),
  ('MR 24 ICNF', 'MR', 'UNM_FSBF', 'Região de Coimbra', 'Arganil'),
  ('PM 09 ICNF', 'PM', 'UNM_FSBF', 'Região de Coimbra', 'Arganil'),
  ('TRATOR_RECHEGA', 'TF', 'UNM_FSBF', 'Região de Coimbra', 'Lousã'),
  ('PM_ICNF_11', 'VALE', 'UNM_FSBF', 'Região de Coimbra', 'Arganil'),
  ('VAFR 02 CNT', 'VT_ICNF', 'GFR', 'Região de Coimbra', 'Lousã'),
  ('VASG03_CNT', 'VT_ICNF', 'GFR', 'Região de Coimbra', 'Lousã'),
  ('VAFR 03 CNT', 'VT_ICNF', 'GFR', 'Região de Coimbra', 'Lousã'),
  ('VGFR 06 CNT', 'VT_ICNF', 'GFR', 'Região de Coimbra', 'Lousã'),
  ('CNAF 08', 'VTEC', 'CNAF', 'Região de Coimbra', 'Figueira da Foz'),
  ('CNAF 03', 'VTEC', 'CNAF', 'Região de Coimbra', 'Lousã'),
  ('CNAF 01', 'VTEC', 'CNAF', 'Região de Coimbra', 'Arganil'),
  ('CNAF 02', 'VTEC', 'CNAF', 'Região de Coimbra', 'Arganil'),
  ('CNAF 04', 'VTEC', 'CNAF', 'Região de Coimbra', 'Góis'),
  ('CNAF 05', 'VTEC', 'CNAF', 'Região de Coimbra', 'Penacova'),
  ('CNAF 13-165', 'VTEC', 'CNAF', 'Região de Coimbra', 'Lousã'),
  ('CNAF 54', 'VTEC', 'CNAF', 'Região de Coimbra', 'Arganil'),
  ('SF 01-163', 'ESF', 'ESF', 'Região de Leiria', 'Porto de Mós'),
  ('SF 02-164', 'ESF', 'ESF', 'Região de Leiria', 'Ansião'),
  ('SF 03-163', 'ESF', 'ESF', 'Região de Leiria', 'Pombal'),
  ('SF 06-163', 'ESF', 'ESF', 'Região de Leiria', 'Pombal'),
  ('SF 06-164', 'ESF', 'ESF', 'Região de Leiria', 'Castanheira de Pêra'),
  ('SF 07-163', 'ESF', 'ESF', 'Região de Leiria', 'Pombal'),
  ('SF 08-164', 'ESF', 'ESF', 'Região de Leiria', 'Pedrógão Grande'),
  ('SF 09-163', 'ESF', 'ESF', 'Região de Leiria', 'Pombal'),
  ('SF 10-163', 'ESF', 'ESF', 'Região de Leiria', 'Pombal'),
  ('SF 11-164', 'ESF', 'ESF', 'Região de Leiria', 'Castanheira de Pêra'),
  ('SF 12-164', 'ESF', 'ESF', 'Região de Leiria', 'Alvaiázere'),
  ('SF 15-164', 'ESF', 'ESF', 'Região de Leiria', 'Ansião'),
  ('SF 17-164', 'ESF', 'ESF', 'Região de Leiria', 'Figueiró Dos Vinhos'),
  ('SF 22-164', 'ESF', 'ESF', 'Região de Leiria', 'Alvaiázere'),
  ('SF 23-164', 'ESF', 'ESF', 'Região de Leiria', 'Pedrógão Grande'),
  ('ESF 02-163', 'ESF', 'ESF', 'Região de Leiria', 'Leiria'),
  ('MR 05 ICNF', 'MR', 'UNM_FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('PM 03 ICNF', 'PM', 'UNM_FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('PM_ICNF_07', 'VALE', 'UNM_FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('VLCI 10 FSBF', 'VLCI', 'FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('VAFR 06 FSBF', 'VLCI', 'FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('VAFR 11 FSBF', 'VLCI', 'FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('VAFR 16 FSBF', 'VLCI', 'FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('VASG02_CNT', 'VT_ICNF', 'GFR', 'Região de Leiria', 'Marinha Grande'),
  ('VAFR 06 CNT', 'VT_ICNF', 'GFR', 'Região de Leiria', 'Marinha Grande'),
  ('VGFR 01 LVT', 'VT_ICNF', 'GFR', 'Região de Leiria', 'Porto de Mós'),
  ('VGFR 03 LVT', 'VT_ICNF', 'GFR', 'Região de Leiria', 'Porto de Mós'),
  ('VGFR 07 CNT', 'VT_ICNF', 'GFR', 'Região de Leiria', 'Marinha Grande'),
  ('CNAF 09', 'VTEC', 'CNAF', 'Região de Leiria', 'Leiria'),
  ('CNAF 07', 'VTEC', 'CNAF', 'Região de Leiria', 'Marinha Grande'),
  ('CNAF 07-163', 'VTEC', 'CNAF', 'Região de Leiria', 'Marinha Grande'),
  ('VAOP 15 FSBF', 'VTEC_ICNF', 'FSBF', 'Região de Leiria', 'Marinha Grande'),
  ('SF 07-117', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Vila Flor'),
  ('SF 10-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Vinhais'),
  ('SF 12-117', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mirandela'),
  ('SF 14-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Miranda do Douro'),
  ('SF 19-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Alfândega da Fé'),
  ('SF 21-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('SF 22-117', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Vila Flor'),
  ('SF 23-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Vinhais'),
  ('SF 28-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mirandela'),
  ('SF 29-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Vimioso'),
  ('SF 33-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Vinhais'),
  ('SF 34-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('SF 35-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('SF 44-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('SF 46-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Vimioso'),
  ('SF 49-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('SF 53-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('SF 54-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('SF 55-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mirandela'),
  ('SF 56-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Miranda do Douro'),
  ('SF 57-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mirandela'),
  ('SF 59-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Mirandela'),
  ('ESF 24-118', 'ESF', 'ESF', 'Terras de Trás-os-Montes', 'Bragança'),
  ('ICNF 1100', 'ESF', 'VN', 'Terras de Trás-os-Montes', 'Bragança'),
  ('ICNF 1101', 'ESF', 'VN', 'Terras de Trás-os-Montes', 'Bragança'),
  ('ICNF 1102', 'ESF', 'VN', 'Terras de Trás-os-Montes', 'Bragança'),
  ('ICNF 1301', 'ESF', 'VN', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('MR 08 ICNF', 'MR', 'UNM_FSBF', 'Terras de Trás-os-Montes', 'Macedo de Cavaleiros'),
  ('MR 12 ICNF', 'MR', 'UNM_FSBF', 'Terras de Trás-os-Montes', 'Macedo de Cavaleiros'),
  ('MR 13 ICNF', 'MR', 'UNM_FSBF', 'Terras de Trás-os-Montes', 'Macedo de Cavaleiros'),
  ('MR 23 ICNF', 'MR', 'UNM_FSBF', 'Terras de Trás-os-Montes', 'Macedo de Cavaleiros'),
  ('MR_ICNF 330', 'MR', 'UNM_FSBF', 'Terras de Trás-os-Montes', 'Mirandela'),
  ('MR ICNF 05', 'MR', 'UNM_FSBF', 'Terras de Trás-os-Montes', 'Mirandela'),
  ('VAFR 09 NRT', 'VT_ICNF', 'GFR', 'Terras de Trás-os-Montes', 'Bragança'),
  ('VGFR 08 NRT', 'VT_ICNF', 'GFR', 'Terras de Trás-os-Montes', 'Bragança'),
  ('CNAF 22', 'VTEC', 'CNAF', 'Terras de Trás-os-Montes', 'Bragança'),
  ('CNAF 34', 'VTEC', 'CNAF', 'Terras de Trás-os-Montes', 'Bragança'),
  ('CNAF 35', 'VTEC', 'CNAF', 'Terras de Trás-os-Montes', 'Miranda do Douro'),
  ('CNAF 33', 'VTEC', 'CNAF', 'Terras de Trás-os-Montes', 'Vinhais'),
  ('VTEC_ICNF_VN12', 'VTEC_ICNF', 'VN', 'Terras de Trás-os-Montes', 'Bragança'),
  ('VTEC_ICNF_VN21', 'VTEC_ICNF', 'VN', 'Terras de Trás-os-Montes', 'Mogadouro'),
  ('VTEC_ICNF_VN31', 'VTEC_ICNF', 'VN', 'Terras de Trás-os-Montes', 'Miranda do Douro'),
  ('SF 41-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 39-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 40-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 12-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Amarante'),
  ('SF 15-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Marco de Canaveses'),
  ('SF 17-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 23-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Amarante'),
  ('SF 26-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Marco de Canaveses'),
  ('SF 31-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Marco de Canaveses'),
  ('SF 34-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Marco de Canaveses'),
  ('SF 36-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Marco de Canaveses'),
  ('SF 39-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 40-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 41-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 43-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 44-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 45-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('SF 46-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Marco de Canaveses'),
  ('ESF 10-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('ESF 35-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Baião'),
  ('SF 21-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Celorico de Basto'),
  ('SF 33-115', 'ESF', 'ESF', 'Tâmega e Sousa', 'Penafiel'),
  ('CNAF 18', 'VTEC', 'CNAF', 'Tâmega e Sousa', 'Amarante'),
  ('CNAF 18-A', 'VTEC', 'CNAF', 'Tâmega e Sousa', 'Amarante'),
  ('SF 01-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Vouzela'),
  ('SF 06-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Castro Daire'),
  ('SF 18-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'São Pedro do Sul'),
  ('SF 08-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Vouzela'),
  ('SF 10-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Sátão'),
  ('SF 11-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Vouzela'),
  ('SF 12-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Oliveira de Frades'),
  ('SF 13-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Sátão'),
  ('SF 14-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Aguiar da Beira'),
  ('SF 15-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Carregal do Sal'),
  ('SF 16-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'São Pedro do Sul'),
  ('SF 17-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'São Pedro do Sul'),
  ('SF 19-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'São Pedro do Sul'),
  ('SF 20-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'São Pedro do Sul'),
  ('SF 21-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Tondela'),
  ('SF 22-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Castro Daire'),
  ('SF 24-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Penalva do Castelo'),
  ('SF 25-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Tondela'),
  ('SF 26-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Vila Nova de Paiva'),
  ('SF 28-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Viseu'),
  ('SF 29-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Tondela'),
  ('SF 30-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Carregal do Sal'),
  ('SF 31-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Viseu'),
  ('SF 32-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Viseu'),
  ('SF 33-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Penalva do Castelo'),
  ('SF 34-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Tondela'),
  ('SF 38-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Castro Daire'),
  ('SF 39-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Tondela'),
  ('SF 40-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Tondela'),
  ('SF 41-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Tondela'),
  ('SF 42-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Vila Nova de Paiva'),
  ('SF 43-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Viseu'),
  ('SF 44-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Carregal do Sal'),
  ('ESF 02-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Viseu'),
  ('ESF 27-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Nelas'),
  ('SF 23-165', 'ESF', 'ESF', 'Viseu Dão-Lafões', 'Santa Comba Dão'),
  ('MR 06 ICNF', 'MR', 'UNM_FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('MR_ICNF 806', 'MR', 'UNM_FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('MR ICNF 04', 'MR', 'UNM_FSBF', 'Viseu Dão-Lafões', 'Mangualde'),
  ('PM 10 ICNF', 'PM', 'UNM_FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('PM_ICNF_08', 'VALE', 'UNM_FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('VFCI 05 FSBF', 'VFCI', 'FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('VLCI 14 FSBF', 'VLCI', 'FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('VAFR 10 FSBF', 'VLCI', 'FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('VAFR 12 FSBF', 'VLCI', 'FSBF', 'Viseu Dão-Lafões', 'Viseu'),
  ('VGFR 02 CNT', 'VT_ICNF', 'GFR', 'Viseu Dão-Lafões', 'Viseu'),
  ('CNAF 13', 'VTEC', 'CNAF', 'Viseu Dão-Lafões', 'Viseu'),
  ('VGFR 03 CNT', 'VTEC_ICNF', 'GFR', 'Viseu Dão-Lafões', 'Viseu')
ON CONFLICT DO NOTHING;

-- 868 rows processed
